import{a as q,S as P,i}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v=15;async function f(o,t,s){const r="https://pixabay.com"+"/api/",a={key:"55157705-9f4ed22218599416e91cc1d5e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};return(await q.get(r,{params:a})).data}const h=document.querySelector(".gallery"),M=new P(".gallery a");function g(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:a,comments:y,downloads:S})=>`
        <li class="gallery-item">
            <a href="${n}">
                <img src="${s}" alt="${e}" loading="lazy" />
            </a>
            <ul class="gallery-info">
                <li><b>Likes</b> ${r}</li>
                <li><b>Views</b> ${a}</li>
                <li><b>Comments</b> ${y}</li>
                <li><b>Downloads</b> ${S}</li>
            </ul>
        </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){h.innerHTML=""}const p=document.querySelector(".loader");function b(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}const L=document.querySelector('button[type="button"]');function x(){L.classList.remove("hidden")}function m(){L.classList.add("hidden")}const B=document.querySelector('input[name="search-text"]'),E=document.querySelector(".form"),O=document.querySelector('button[type="button"]');let d,l,u;E.addEventListener("submit",async o=>{if(o.preventDefault(),l=1,$(),document.querySelector(".end-message").classList.add("hidden"),m(),b(),d=B.value,d===""){i.show({title:"Empty form",message:'Please add some text and click "Search"',color:"blue"}),c();return}try{const t=await f(d,l);if(u=Math.ceil(t.totalHits/v),t.total===0){i.show({title:"Try again",message:"Sorry, there are no images matching your search query. Please try again!",color:"blue"}),c();return}g(t.hits)}catch{i.show({title:"Error",message:"Something went wrong in createGallery",color:"red"})}finally{c(),w()}});O.addEventListener("click",async o=>{m(),b(),l+=1;try{const t=await f(d,l);if(t.total===0){i.show({title:"Try again",message:"Sorry, there are no images matching your search query. Please try again!",color:"blue"}),c();return}g(t.hits);const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}catch{i.show({title:"Error",message:"Something went wrong in createGallery",color:"red"})}finally{c(),w()}});function w(){if(u!==0){if(l>=u){m(),document.querySelector(".end-message").classList.remove("hidden");return}x()}}
//# sourceMappingURL=index.js.map
