import{a as v,S as P,i}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const y=15;async function f(o,t){const e="https://pixabay.com"+"/api/",r={key:"55157705-9f4ed22218599416e91cc1d5e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:y};return(await v.get(e,{params:r})).data}const h=document.querySelector(".gallery"),$=new P(".gallery a");function g(o){const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:a,comments:S,downloads:q})=>`
        <li class="gallery-item">
            <a href="${s}">
                <img src="${n}" alt="${e}" loading="lazy" />
            </a>
            <ul class="gallery-info">
                <li><b>Likes</b> ${r}</li>
                <li><b>Views</b> ${a}</li>
                <li><b>Comments</b> ${S}</li>
                <li><b>Downloads</b> ${q}</li>
            </ul>
        </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){h.innerHTML=""}const p=document.querySelector(".loader");function b(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}const L=document.querySelector('button[type="button"]');function E(){L.classList.remove("hidden")}function m(){L.classList.add("hidden")}const x=document.querySelector('input[name="search-text"]'),B=document.querySelector(".form"),O=document.querySelector('button[type="button"]');let u,l,d;B.addEventListener("submit",async o=>{if(o.preventDefault(),l=1,M(),document.querySelector(".end-message").classList.add("hidden"),m(),b(),u=x.value,u===""){i.show({title:"Empty form",message:'Please add some text and click "Search"',color:"blue"}),c();return}try{const t=await f(u,l);if(d=Math.ceil(t.totalHits/y),t.total===0){i.show({title:"Try again",message:"Sorry, there are no images matching your search query. Please try again!",color:"blue"}),c();return}g(t.hits)}catch{i.show({title:"Error",message:"Something went wrong in createGallery",color:"red"})}finally{c(),w()}});O.addEventListener("click",async o=>{m(),b(),l+=1;try{const t=await f(u,l);if(t.total===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"blue"}),c();return}g(t.hits);const n=document.querySelector(".gallery-item");if(n){const s=n.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}catch(t){i.show({title:"Error",message:`Error received: ${t}`,color:"red"})}finally{c(),w()}});function w(){if(d!==0){if(l>=d){m(),i.show({message:"We're sorry, but you've reached the end of search results.",color:"blue"});return}E()}}
//# sourceMappingURL=index.js.map
