import{a as q,S as P,i}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m=15;async function f(o,t){const e="https://pixabay.com"+"/api/",r={key:"55157705-9f4ed22218599416e91cc1d5e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:m};return(await q.get(e,{params:r})).data}const y=document.querySelector(".gallery"),$=new P(".gallery a");function g(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:a,comments:S,downloads:v})=>`
        <li class="gallery-item">
            <a href="${n}">
                <img src="${s}" alt="${e}" loading="lazy" />
            </a>
            <ul class="gallery-info">
                <li><b>Likes</b> ${r}</li>
                <li><b>Views</b> ${a}</li>
                <li><b>Comments</b> ${S}</li>
                <li><b>Downloads</b> ${v}</li>
            </ul>
        </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),$.refresh()}function E(){y.innerHTML=""}const p=document.querySelector(".loader");function b(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}const L=document.querySelector('button[type="button"]');function M(){L.classList.remove("hidden")}function d(){L.classList.add("hidden")}const x=document.querySelector('input[name="search-text"]'),B=document.querySelector(".form"),O=document.querySelector('button[type="button"]');let u,c,h;B.addEventListener("submit",async o=>{if(o.preventDefault(),c=1,E(),d(),b(),u=x.value.trim(),u===""){i.show({title:"Empty form",message:'Please add some text and click "Search"',color:"blue"}),l();return}try{const t=await f(u,c);if(h=Math.ceil(t.totalHits/m),t.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"blue"}),l();return}g(t.hits),w()}catch(t){i.show({title:"Error",message:`Error received: ${t}`,color:"red"})}finally{l()}});O.addEventListener("click",async o=>{d(),b(),c+=1;try{const t=await f(u,c);if(t.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"blue"}),l();return}g(t.hits),w();const s=document.querySelector(".gallery-item");if(s){const n=s.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}catch(t){c-=1,d(),i.show({title:"Error",message:`Error received: ${t}`,color:"red"})}finally{l()}});function w(){if(h!==0){if(c>=h){d(),i.show({message:"We're sorry, but you've reached the end of search results.",color:"blue"});return}M()}}
//# sourceMappingURL=index.js.map
